### ISSUE TITLE
Pourquoi une variable de classe ici et pas d'instance?

### ISSUE THREAD

**Issue by timoguic** [flenoir/mc_gyver_maze#1]
https://github.com/flenoir/mc_gyver_maze/blob/810ee238914170774c20933d6110106a39bdacf3/app.py#L24

**Comment by flenoir** [comment]
Je me disais que cette variable ne devait pas être accessible depuis l’extérieur et surtout que cette variable est propre à la classe. 
Comme elle est vide et qu'elle est remplie par les informations venant d'une instance, je comprend que ce n'est donc pas pertinent. Je vais revoir ce point.

**Comment by flenoir** [comment]
ce n'est pas une variable de classe, corrigé en variable d'instance
