### ISSUE TITLE
A quoi servent ces variables d'instance?

### ISSUE THREAD

**Issue by timoguic** [flenoir/mc_gyver_maze#2]
https://github.com/flenoir/mc_gyver_maze/blob/810ee238914170774c20933d6110106a39bdacf3/app.py#L39

**Comment by flenoir** [comment]
le paramètre char1_pos est un tuple qui contient la position de l'instance Mac_gyver. 
En relisant le code, je vois que self.char1_pos n'est jamais utilisé dans la fonction. 

Je pense que j'ai fais des confusions avec les attributs créés dans les constructeurs __init__

**Comment by flenoir** [comment]
code modifié sur ce point
